### ISSUE TITLE
missing ...

### ISSUE THREAD

**Issue by Nitrinax** [mrmlnc/vscode-apache#1] opened 2016-09-10 07:23 UTC
following syntax commands are not highlighted on windows
- ErrorLogFormat
- GlobalLog
- PHPIniDir
- SSLHonorCipherOrder
- SSLCompression
- SSLUseStapling
- SSLStapling*
- SSLCARevocationCheck
- SSLSRPVerifierFile
- SSLSessionTickets
- RequestReadTimeout
- ProxyHTML*
- MaxRanges

**Comment by mrmlnc** [comment] 2016-09-10 09:18
Hello, @Nitrinax,

Firstly, thank you for opening this issue. This repository uses grammar developed by @colinta to preserve the similarity of highlighting between editors.

I moved this issue to https://github.com/colinta/ApacheConf.tmLanguage repository and once the problem is resolved, I will update this plugin.

You can help fix the problem, if you provide small code examples.

I won't close this issue, to monitor the situation.

**Comment by mrmlnc** [comment] 2016-09-13 08:21
Available in v1.1.0

**Closed as completed by mrmlnc** 2016-09-13 08:21 UTC
Labels: enhancement, upstream
